export interface DocMeta {
  slug: string;
  title: string;
  order: number;
}

// Inline doc content at build time — no fs.readFileSync needed on Workers
const DOCS: Record<string, { title: string; content: string }> = {
  "getting-started": {
    title: "Getting Started",
    content: `# Getting Started

Terso is a CLI that keeps your AI coding agents on the same page as you. The fastest path is offline: write project rules in \`AGENTS.md\` and let \`terso emit\` compile them into the config files each agent expects.

## Install

\`\`\`bash
npm install -g terso-cli
\`\`\`

Or use without installing:

\`\`\`bash
npx terso-cli emit
\`\`\`

## Quick start

### 1. Initialize in your project

\`\`\`bash
cd ~/projects/my-app
terso init
\`\`\`

This creates a \`.terso/\` directory and scaffolds an \`AGENTS.md\` at the project root if you don't already have one.

### 2. Edit AGENTS.md

Write your project rules once — conventions, commands, "don'ts". This is the single source of truth.

### 3. Compile to per-agent config files

\`\`\`bash
terso emit
\`\`\`

Output:

\`\`\`
  create   CLAUDE.md
  create   .cursorrules
  create   .github/copilot-instructions.md

Emitted 3 file(s) from AGENTS.md (0 unchanged).
\`\`\`

Each emitted file starts with a marker comment so re-running \`emit\` is safe and won't clobber files you maintain by hand.

### 4. Your AI agents read it

Cursor reads \`.cursorrules\`. Claude Code reads \`CLAUDE.md\`. Copilot reads \`.github/copilot-instructions.md\`. They all get the same instructions, compiled from one source.

## Going further

Want richer project memory — captured decisions, cross-project search, shared ops? Connect to [Omnus](https://omnus.dev) and use \`terso sync\` / \`capture\` / \`search\`. See [Standalone vs Connected](/docs/standalone-vs-connected).`,
  },
  "cli-reference": {
    title: "CLI Reference",
    content: `# CLI Reference

## terso emit

Compile \`AGENTS.md\` into per-agent config files at the project root.

\`\`\`bash
terso emit
terso emit --check       # CI gate — fail if any file would change
terso emit --dry-run     # preview without writing
terso emit --watch       # re-emit on every save of AGENTS.md
terso emit --targets claude,cursor
terso emit --force       # overwrite files that aren't marked as terso-generated
\`\`\`

**Flags:**
- \`--targets <list>\` — comma-separated subset: \`claude\`, \`cursor\`, \`copilot\`
- \`--check\` — exit non-zero if any target file would change. Use in CI.
- \`--dry-run\` — show what would change without writing
- \`--force\` — overwrite existing files even if not marked as generated by terso
- \`--watch\` — re-emit on every save of \`AGENTS.md\`

By default, \`emit\` writes to whichever targets look active in your repo (detected via presence of \`.cursor/\`, \`CLAUDE.md\`, \`.github/\`, etc.). On a fresh repo with no hints, it writes all three.

\`emit\` works without Omnus — it's pure local file compilation.

## terso init

Initialize Terso in a project directory.

\`\`\`bash
terso init
terso init --project-id my-project
terso init --skip-verify           # skip Omnus project verification
\`\`\`

Creates \`.terso/\` and scaffolds \`AGENTS.md\` at the project root if missing.

## terso capture

Capture knowledge from the terminal (requires Omnus).

\`\`\`bash
terso capture "your text here"
\`\`\`

If offline, captures are stored locally and flushed on next \`terso sync\`.

## terso auth

Manage Omnus API authentication.

\`\`\`bash
terso auth set <token>   # save API token
terso auth status        # show auth status
terso auth clear         # remove stored token
\`\`\`

Tokens are stored in \`~/.terso/config.json\`. Override with \`TERSO_API_TOKEN\` env var.

## terso sync

Pull project context from Omnus and write to \`.terso/generated/\`.

\`\`\`bash
terso sync
terso sync --force      # overwrite even if unchanged
terso sync --dry-run    # preview without writing
\`\`\`

## terso search

Search project knowledge (requires Omnus).

\`\`\`bash
terso search "stripe webhook setup"
\`\`\`

## terso status

Show current project knowledge status.

\`\`\`bash
terso status
\`\`\`

## terso doctor

Check project health and configuration.

\`\`\`bash
terso doctor
\`\`\`

Verifies: \`.terso/\` present, API connectivity, \`.gitignore\` correctness.

## terso watch

Watch \`.terso/\` source files and auto-sync from Omnus on change.

\`\`\`bash
terso watch
terso watch --interval 5000
\`\`\`

For watching \`AGENTS.md\` instead, use \`terso emit --watch\` — that's the offline-only flow.

## terso compile

Compile local \`.terso/\` source files into a single \`CURRENT_CONTEXT.md\` artifact (offline mode for the Omnus flow).

\`\`\`bash
terso compile
\`\`\`

Note: \`compile\` is for the Omnus-style \`.terso/generated/\` flow. For the AGENTS.md → per-agent config flow, use \`emit\`.

## terso mcp

Run an MCP server over stdio that exposes project context to AI agent clients (Claude Code, Cursor, Codex).

\`\`\`bash
terso mcp                            # run the server (used by your client)
terso mcp install --client claude    # print install snippet
terso mcp install --client cursor
terso mcp install --client codex
\`\`\`

See [MCP Server](/docs/mcp-server) for setup and tool details.`,
  },
  "agents-md-compiler": {
    title: "AGENTS.md Compiler",
    content: `# AGENTS.md Compiler

Most teams using AI coding agents end up maintaining the same project rules in 3–4 places: \`.cursorrules\` for Cursor, \`CLAUDE.md\` for Claude Code, \`.github/copilot-instructions.md\` for Copilot, often \`AGENTS.md\` too. They drift. People update one and forget the others.

\`terso emit\` makes \`AGENTS.md\` canonical and treats the rest as compilation output.

\`\`\`
AGENTS.md  →  CLAUDE.md
            →  .cursorrules
            →  .github/copilot-instructions.md
\`\`\`

## How it works

1. You write project rules once in \`AGENTS.md\`.
2. \`terso emit\` writes them out to whichever per-agent files your repo uses.
3. Each emitted file starts with a marker comment so re-running \`emit\` is safe and won't clobber files you maintain by hand.

## Why AGENTS.md?

It has the broadest cross-tool acceptance and is already used as a canonical format by Codex and others. Picking an existing standard means no new file format to learn.

## Auto-detection

\`emit\` only writes to targets whose presence hints exist in your repo:

| Agent | Detected via |
|---|---|
| Claude Code | \`CLAUDE.md\` or \`.claude/\` |
| Cursor | \`.cursorrules\` or \`.cursor/\` |
| GitHub Copilot | \`.github/copilot-instructions.md\` |

On a fresh repo with no hints, \`emit\` writes all three so you can pick what to keep.

## Safety

\`emit\` won't overwrite files you maintain by hand. The first write tags each output file with this marker:

\`\`\`
<!-- Generated by terso from AGENTS.md. Do not edit; run \`terso emit\` to update. -->
\`\`\`

Re-runs only overwrite files that have this marker. To overwrite an unmarked file, use \`--force\`.

## CI gate

Add a check to your pipeline so \`AGENTS.md\` and the emitted files can never drift:

\`\`\`yaml
# .github/workflows/agents.yml
name: agents-config-sync
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx terso-cli emit --check
\`\`\`

This fails the build if anyone hand-edits \`CLAUDE.md\` or \`.cursorrules\` without updating the canonical \`AGENTS.md\`.

## Watch mode

While iterating on rules, run:

\`\`\`bash
terso emit --watch
\`\`\`

Every save of \`AGENTS.md\` re-emits the per-agent files immediately. Pair this with your editor's autosave for a tight feedback loop.

## Cherry-picking targets

If you only use Claude Code and Cursor:

\`\`\`bash
terso emit --targets claude,cursor
\`\`\`

Or remove the unwanted file once and \`emit\` will skip it on subsequent runs (no presence hint = not emitted).`,
  },
  "mcp-server": {
    title: "MCP Server",
    content: `# MCP Server

\`terso mcp\` runs a [Model Context Protocol](https://modelcontextprotocol.io) server that exposes your project context to any agent client — Claude Code, Cursor, Codex, Cline. One config block, every agent reads the same project memory.

## Install

The server ships with the CLI. Print the install snippet for your client and paste it into the right config file:

### Claude Code

\`\`\`bash
terso mcp install --client claude
\`\`\`

Add the printed JSON to \`.mcp.json\` (project-level) or \`~/.claude.json\` (user-level):

\`\`\`json
{
  "mcpServers": {
    "terso": { "command": "terso", "args": ["mcp"] }
  }
}
\`\`\`

Restart Claude Code and the \`terso_*\` tools will appear.

### Cursor

\`\`\`bash
terso mcp install --client cursor
\`\`\`

Add to \`~/.cursor/mcp.json\` (user-level) or \`.cursor/mcp.json\` (project-level):

\`\`\`json
{
  "mcpServers": {
    "terso": { "command": "terso", "args": ["mcp"] }
  }
}
\`\`\`

### Codex CLI

\`\`\`bash
terso mcp install --client codex
\`\`\`

Add to \`~/.codex/config.toml\`:

\`\`\`toml
[mcp_servers.terso]
command = "terso"
args = ["mcp"]
\`\`\`

## Tools

| Tool | Purpose | Auth |
|---|---|---|
| \`terso_get_context\` | Returns \`AGENTS.md\` plus any synced files in \`.terso/generated/\` | none |
| \`terso_search\` | Search captured knowledge in Omnus | required |
| \`terso_capture\` | Capture a fragment to Omnus | required |

### terso_get_context

Returns the canonical project context. Works offline. Always available.

The agent calls this once per session (or as needed) to ground itself in your project's rules and current state. Includes:

- \`AGENTS.md\` from the project root
- Every \`.md\` file in \`.terso/generated/\` (if you've connected to Omnus and run \`terso sync\`)

### terso_search

\`\`\`json
{
  "query": "stripe webhook setup",
  "limit": 5
}
\`\`\`

Searches your project knowledge in Omnus and returns ranked results with kind, scope, score, and date. Requires \`TERSO_API_TOKEN\` or a token saved via \`terso auth set\`.

### terso_capture

\`\`\`json
{
  "text": "Switched auth to Supabase — RLS was the dealbreaker",
  "scope": "project"
}
\`\`\`

Sends a knowledge fragment to Omnus for ingestion. Useful when you want the agent to record decisions it just helped you make. Returns the ingestion id.

## Standalone vs connected

| Tool | Standalone (no Omnus) | Connected |
|---|---|---|
| \`terso_get_context\` | Returns AGENTS.md only | + synced \`.terso/generated/\` files |
| \`terso_search\` | Returns auth error | Full search across project |
| \`terso_capture\` | Returns auth error | Captures to Omnus |

You can use the MCP server in standalone mode just for \`terso_get_context\` — agents get your AGENTS.md without any plugin or per-client integration code.

## Troubleshooting

**Tools don't show up after install.** Restart your agent client. MCP server connections are typically established on client startup.

**\`terso_search\` returns "No Omnus API token".** Run \`terso auth set <token>\` in the project directory, or set \`TERSO_API_TOKEN\` in your environment.

**Server keeps crashing.** Run \`terso mcp\` directly in a terminal and send a JSON-RPC \`initialize\` request — it should respond on stdout. If \`terso\` is not on PATH, use the full path in your client config.`,
  },
  "terso-format": {
    title: ".terso/ Format",
    content: `# .terso/ Directory Format

The \`.terso/\` directory is for the connected-mode flow — context pulled from Omnus into your project. (For the offline AGENTS.md → per-agent config flow, see [AGENTS.md Compiler](/docs/agents-md-compiler).)

## Directory structure

\`\`\`
project-root/
  AGENTS.md                # canonical agent instructions (offline flow)
  .terso/
    project.json           # project config (Omnus connection)
    .gitignore             # excludes generated/ from git
    PROJECT.md             # hand-maintained: what this project is
    ARCHITECTURE.md        # hand-maintained: current system design
    STATUS.md              # hand-maintained: current state, roadmap
    DECISIONS/
      2026-05.md           # hand-maintained: monthly decision log
    generated/             # machine-generated, overwritten on sync
      CURRENT_CONTEXT.md
      ...                  # additional files from Omnus
\`\`\`

## Hand-maintained vs generated

**Hand-maintained files** (committed to git):
- \`AGENTS.md\` (project root) — single source for the emit flow
- \`.terso/PROJECT.md\` — what this project is, who it's for
- \`.terso/ARCHITECTURE.md\` — current system design
- \`.terso/STATUS.md\` — current state, roadmap
- \`.terso/DECISIONS/\` — monthly decision logs (append-only ledger)

**Generated files** (\`.terso/generated/\` is in \`.gitignore\`):
- Overwritten on every \`terso sync\`
- Include YAML frontmatter with timestamps and source IDs
- Agents should treat these as current but disposable

## Generated file frontmatter

Every generated file starts with:

\`\`\`yaml
---
generated_at: "2026-05-09T10:00:00Z"
expires_at: "2026-05-10T10:00:00Z"
source_ids: ["mem_123", "mem_456"]
generator: "terso-cli v0.2.0"
freshness: "current"
---
\`\`\`

## project.json

\`\`\`json
{
  "projectId": "my-project",
  "apiUrl": "https://omnus.dev",
  "detectedFrom": "package.json",
  "verified": true,
  "createdAt": "2026-05-09T10:00:00Z"
}
\`\`\`

## State vs ledger documents

| If the content is... | Type | Update pattern |
|---|---|---|
| Current truth that replaces old truth | State | Overwrite the file |
| A new event that happened | Ledger | Append with timestamp |
| A temporary observation | Exhaust | Short TTL, auto-expire |`,
  },
  "agent-integration": {
    title: "Agent Integration",
    content: `# Agent Integration

Terso ships two ways for AI coding agents to read your project context. Pick whichever fits — or use both.

## 1. The emit flow (offline, recommended start)

You write \`AGENTS.md\` once. \`terso emit\` compiles it into the config file each agent expects:

| Agent | File |
|---|---|
| Claude Code | \`CLAUDE.md\` |
| Cursor | \`.cursorrules\` |
| GitHub Copilot | \`.github/copilot-instructions.md\` |

Each agent reads its native file at the project root. No plugins, no MCP, no API calls. See [AGENTS.md Compiler](/docs/agents-md-compiler) for details.

## 2. The Omnus flow (connected, richer memory)

For richer, dynamically-updated context — captured decisions, cross-project search, shared ops — connect to [Omnus](https://omnus.dev) and run \`terso sync\`. Files land in \`.terso/generated/\` and are read by file-aware agents.

### Cursor

Cursor automatically indexes all files in your project directory. Reference Terso files from \`.cursorrules\` (which \`terso emit\` keeps in sync with \`AGENTS.md\`):

\`\`\`
Always read .terso/generated/CURRENT_CONTEXT.md before making
architectural decisions.
\`\`\`

### Claude Code

Claude Code reads \`CLAUDE.md\` automatically. Add Terso references to your \`AGENTS.md\` (the canonical source) and they'll flow into \`CLAUDE.md\` on the next \`emit\`:

\`\`\`markdown
## Before you start
1. Run \\\`terso sync\\\` to pull current context.
2. Read .terso/generated/CURRENT_CONTEXT.md for project state.
3. Reference .terso/STATUS.md for current priorities.
\`\`\`

### GitHub Copilot

Since \`.terso/generated/\` is in \`.gitignore\`, Copilot won't see generated files by default. Two options:

**Commit generated files** (they're not secret):

\`\`\`bash
# Remove from .terso/.gitignore, commit them
terso sync
git add .terso/generated/
git commit -m "chore: sync terso context"
\`\`\`

**Or run sync in CI** so context is always fresh:

\`\`\`yaml
# .github/workflows/sync-context.yml
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx terso-cli sync
      - run: |
          git add .terso/generated/
          git commit -m "chore: sync terso context" || true
          git push
\`\`\`

## Any file-aware agent

If your agent reads files in the project directory, it can read Terso output. Both flows produce plain Markdown. No special parsing required.`,
  },
  "standalone-vs-connected": {
    title: "Standalone vs Connected",
    content: `# Standalone vs Connected Mode

Terso works in two modes. Standalone is free, offline, and gets you the AGENTS.md compiler immediately. Connected adds richer project memory backed by [Omnus](https://omnus.dev).

## Standalone mode (recommended start)

No Omnus account, no network, no auth. Free, open source.

\`\`\`bash
npm install -g terso-cli
cd ~/projects/my-app
terso init
# edit AGENTS.md
terso emit
\`\`\`

What works in standalone:
- \`terso emit\` — compile \`AGENTS.md\` to \`CLAUDE.md\`, \`.cursorrules\`, \`.github/copilot-instructions.md\`
- \`emit --watch\` — live re-compile on save
- \`emit --check\` — CI gate to prevent drift
- \`terso mcp\` — MCP server exposes \`AGENTS.md\` to any agent via [MCP](/docs/mcp-server)
- \`terso compile\` — combine \`.terso/\`-tracked source docs into a single context artifact

What's missing without Omnus:
- No captured decisions from the terminal
- No cross-project search
- No shared operational knowledge across projects
- No nightly state consolidation
- No portfolio health monitoring

## Connected mode

Add an Omnus account to unlock the capture/sync/search pipeline.

\`\`\`bash
terso auth set <your-api-token>
terso capture "switched auth to Supabase — RLS was the dealbreaker"
terso sync
\`\`\`

What's added:
- Capture from CLI, web, email, or webhooks
- LLM classification and dedup
- Cross-project knowledge search
- Shared ops compiled across all your projects
- Nightly state consolidation
- Review queue for uncertain items
- Portfolio health monitoring

## Switching modes

You don't have to choose. Connected mode is purely additive — \`emit\` keeps working regardless.

Check connection status:

\`\`\`bash
terso doctor
\`\`\`

Clear the API token to fall back to standalone:

\`\`\`bash
terso auth clear
\`\`\``,
  },
};

const SLUG_ORDER = [
  "getting-started",
  "cli-reference",
  "agents-md-compiler",
  "mcp-server",
  "terso-format",
  "agent-integration",
  "standalone-vs-connected",
];

export function getAllDocs(): DocMeta[] {
  return SLUG_ORDER.map((slug, i) => ({
    slug,
    title: DOCS[slug].title,
    order: i,
  }));
}

export function getDocBySlug(
  slug: string
): { meta: DocMeta; content: string } | null {
  const doc = DOCS[slug];
  if (!doc) return null;
  const order = SLUG_ORDER.indexOf(slug);
  return {
    meta: { slug, title: doc.title, order },
    content: doc.content,
  };
}

export function getDocSlugs(): string[] {
  return SLUG_ORDER;
}

export interface NavGroup {
  label: string;
  items: DocMeta[];
}

export function getNavGroups(): NavGroup[] {
  const docs = getAllDocs();
  return [
    {
      label: "Getting Started",
      items: docs.filter((d) =>
        ["getting-started", "cli-reference"].includes(d.slug)
      ),
    },
    {
      label: "Concepts",
      items: docs.filter((d) =>
        ["agents-md-compiler", "mcp-server", "terso-format", "agent-integration"].includes(d.slug)
      ),
    },
    {
      label: "Modes",
      items: docs.filter((d) =>
        ["standalone-vs-connected"].includes(d.slug)
      ),
    },
  ];
}
