#!/usr/bin/env node
// Generates lib/blog.ts by inlining markdown from ../terso-cli/content/blog/*.md.
// Inlining (rather than runtime fs reads) is required because the production
// target is Cloudflare Workers via OpenNext, where node fs is not available.
//
// Run after any change to the source markdown:
//   node scripts/sync-blog.mjs
//
// Reads frontmatter via a tiny parser; we don't pull in gray-matter to keep
// the build dependency-free.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '..', '..', 'terso-cli', 'content', 'blog');
const OUT = resolve(here, '..', 'lib', 'blog.ts');

function parseFrontmatter(src) {
  if (!src.startsWith('---\n')) return { meta: {}, body: src };
  const end = src.indexOf('\n---\n', 4);
  if (end === -1) return { meta: {}, body: src };
  const fmText = src.slice(4, end);
  const body = src.slice(end + 5);
  const meta = {};
  let currentKey = null;
  let currentList = null;
  for (const rawLine of fmText.split('\n')) {
    if (!rawLine.trim()) continue;
    if (rawLine.startsWith('  - ') && currentList) {
      currentList.push(rawLine.slice(4).trim());
      continue;
    }
    const m = rawLine.match(/^([a-zA-Z_-]+):\s*(.*)$/);
    if (!m) continue;
    const [, key, value] = m;
    currentKey = key;
    if (value === '') {
      currentList = [];
      meta[key] = currentList;
    } else if (value.startsWith('[') && value.endsWith(']')) {
      meta[key] = value
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
      currentList = null;
    } else {
      meta[key] = value.replace(/^["']|["']$/g, '');
      currentList = null;
    }
  }
  return { meta, body };
}

const files = readdirSync(SRC)
  .filter((f) => f.endsWith('.md'))
  .sort();

const posts = files.map((file) => {
  const raw = readFileSync(join(SRC, file), 'utf-8');
  const { meta, body } = parseFrontmatter(raw);
  const slug = meta.slug || basename(file, '.md').replace(/^\d+-/, '');
  return {
    file,
    slug,
    title: meta.title || file,
    date: meta.date || '',
    status: meta.status || 'draft',
    tags: meta.tags || [],
    note: meta.note || '',
    references: meta.references || [],
    body: body.trim(),
  };
});

posts.sort((a, b) => (b.date < a.date ? -1 : b.date > a.date ? 1 : 0));

function js(value) {
  return JSON.stringify(value);
}

const out = `// AUTO-GENERATED by scripts/sync-blog.mjs from ../terso-cli/content/blog/*.md.
// Do not hand-edit. Re-run \`node scripts/sync-blog.mjs\` after changing
// source markdown in terso-cli. Inlining is required for Cloudflare Workers.

export interface BlogMeta {
  slug: string;
  title: string;
  date: string;
  status: 'draft' | 'published';
  tags: string[];
  note?: string;
  references: string[];
}

export interface BlogPost {
  meta: BlogMeta;
  content: string;
}

const POSTS: BlogPost[] = [
${posts
  .map(
    (p) => `  {
    meta: {
      slug: ${js(p.slug)},
      title: ${js(p.title)},
      date: ${js(p.date)},
      status: ${js(p.status)} as 'draft' | 'published',
      tags: ${js(p.tags)},${p.note ? `\n      note: ${js(p.note)},` : ''}
      references: ${js(p.references)},
    },
    content: ${JSON.stringify(p.body)},
  },`
  )
  .join('\n')}
];

export function getAllPosts(opts: { includeDrafts?: boolean } = {}): BlogPost[] {
  return POSTS.filter((p) => opts.includeDrafts || p.meta.status === 'published');
}

export function getPostBySlug(slug: string): BlogPost | null {
  return POSTS.find((p) => p.meta.slug === slug) ?? null;
}

export function getPostSlugs(opts: { includeDrafts?: boolean } = {}): string[] {
  return getAllPosts(opts).map((p) => p.meta.slug);
}
`;

writeFileSync(OUT, out, 'utf-8');
console.log(`wrote ${OUT}  (${posts.length} posts)`);
